### ISSUE TITLE
Retry policy

### ISSUE THREAD

**Issue by jstaro** [GitHub4Eddy/tibber_live#3]
Hi,

We're seeing quite a lot of WebSocket reconnect attempts that trigger our rate limiting from your integration towards the Tibber API.

The most common user-agents in question are:

- Tibber_Live/2.2 Fibaro/HC3 Firmware/5.140.17
- Tibber_Live/2.4 Fibaro/HC3 Firmware/5.140.17

Would it be possible to look into implementing an exponential backoff retry policy for this integration, do you think?

If it helps, I could look into our logs to try to see the underlying cause for disconnects; perhaps there are fatal cases where you do not want to reconnect at all. Let me know if you want some details.

Best,
Jon
Tibber

**Comment by GitHub4Eddy** [comment]
Hi Jon,

that is already implemented in the QuickApp (version 2.3) since December last year 2022. (And the latest version is 3.0 ) These are the releases notes: 

Version 2.3 (beta 8th December 2022)
- Improved the 60 seconds interval child devices update, it now never skips a beat
- Added translation for English (en), Dutch (nl), Swedish (se), Norwegian (no)
- Changed the json response for the debugLevel=4 Offline Simulation mode, the date/time format was wrong
- Added random (jitter) reconnection handleDisconnected and handleError between 10 and 15 seconds
- Added random (jitter) reconnection interval handleDisconnected and handleError plus between 1 and 10 seconds
- Added exponential backoff (increasing delay) between each timeout. The increase is limited to 10 times the value in the quickapp reconnect variable.

**Comment by GitHub4Eddy** [comment]
Hi @jstaro 

Did you read my reply?
